blank_issues_enabled: false
contact_links:
  - name: KodeKloud Forum
    url: https://community.kodekloud.com/
    about: Please use the Communuity Forum to ask about anything unrelated to Kubernetes the Hard Way.
